force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>Package</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Package ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/Package_Heigth__c.field-meta.xml
<CustomField>
    <fullName>Package_Heigth__c</fullName>
    <label>Package Height (m)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Package_Lenght__c.field-meta.xml
<CustomField>
    <fullName>Package_Lenght__c</fullName>
    <label>Package Length (m)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Package_Status__c.field-meta.xml
<CustomField>
    <fullName>Package_Status__c</fullName>
    <label>Package Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In-Transit</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/fields/Package_Weidth__c.field-meta.xml
<CustomField>
    <fullName>Package_Weidth__c</fullName>
    <label>Package Width (m)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Shipment__c.field-meta.xml
<CustomField>
    <fullName>Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>Shipment__c</referenceTo>
    <relationshipLabel>Packages</relationshipLabel>
    <relationshipName>Packages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Weight_KG__c.field-meta.xml
<CustomField>
    <fullName>Weight_KG__c</fullName>
    <label>Weight (kg)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <label>Shipment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/In_transit_Date__c.field-meta.xml
<CustomField>
    <fullName>In_transit_Date__c</fullName>
    <label>In-transit Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Shipment_Status__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Status__c</fullName>
    <label>Shipment Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In-Transit</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateEstimatedDeliveryDateTest.cls
@isTest
private class UpdateEstimatedDeliveryDateTest {
    @isTest
    static void testEstimatedDeliveryDate() {
        // test data for dimensions records 
        Shipment__c shipment = new Shipment__c(Shipment_Status__c = 'In-Transit', In_transit_Date__c = System.today());
        insert shipment;
        
        Package__c package1 = new Package__c(Shipment__c = shipment.Id, Package_Status__c = 'In-Transit', Weight_KG__c = 100, Package_Heigth__c = 10, Package_Weidth__c = 5, Package_Lenght__c = 8);
        Package__c package2 = new Package__c(Shipment__c = shipment.Id, Package_Status__c = 'In-Transit', Weight_KG__c = 150 , Package_Heigth__c = 8, Package_Weidth__c = 3, Package_Lenght__c = 6);
        Package__c package3 = new Package__c(Shipment__c = shipment.Id, Package_Status__c = 'In-Transit', Weight_KG__c = 200 , Package_Heigth__c = 6, Package_Weidth__c = 4, Package_Lenght__c = 12);
        insert new List<Package__c>{package1, package2, package3};
        
        // Trigger the update
        Test.startTest();
        update shipment;
        Test.stopTest();
        
        // Retrieve the updated shipment record
        shipment = [SELECT Id, Estimated_Delivery_Date__c FROM Shipment__c WHERE Id = :shipment.Id];
        
        // Verify the expected estimated delivery date
        Date esDate = System.today().addDays(134); // Assuming the logic in the trigger sets the estimated delivery date to 134 days to the future
        System.assertEquals(esDate, shipment.Estimated_Delivery_Date__c);
    }
}